### ISSUE TITLE
Crash in rankdata

### ISSUE THREAD

**Issue by s-andrews** [s-andrews/10XQC#12]
http://10xqc.com/10xqc.cgi?action=rankdata&ids=10,11,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30

The bottom of the output has this:

```
		]<h1>Software error:</h1>
<pre>Couldn't find rank data for id 17 at /data/private/10XQC/www/10xqc.cgi line 188.
```

**Comment by s-andrews** [comment]
This happens because you can have blank report_sample_id fields (which seems odd so it might be a problem with the parser?) and I was checking for data in the field rather than it just being defined.

I've patched it now, but it might indicate another problem upstream.

**Comment by ewels** [comment]
I think that we have a mixture of old and new (refactored) code here. We used to use `report_sample_id` for returning these results but changed to use the database row instead. So `$sample_id` is a field that's parsed from the report (no longer returned in this call), whereas we use `$id` when returning the data which is the database row ID.

I imagine that `$sample_id` is blank in this case because of the new feature I added which allows users to ignore specific fields when submitting data. This was the exact use case actually, as the sample IDs can have identifying / sensitive information.

Phil
